### ISSUE TITLE
First setup - Graphics autoconfig - crash

### ISSUE THREAD

**Issue by ruifscouto** [HikariKnight/rsu-client#63] opened 2015-06-23 13:30 UTC
@HikariKnight 

Hey,
I've just started using this on El Capitan, trying to bypass the fact that the official client requires Java 6 which can't installed in OS X anymore.
When rsu is done fetching updated it shows me the first use screen, saying:
Graphics Setup
This is your first time playing. Cllick below to auto-choose best graphical settings.

I then click auto-setup and the client crashes.

**Comment by ivanpu** [comment] 2015-06-26 21:17
Mac is not my area, maybe @HikariKnight can help...

**Comment by HikariKnight** [comment] 2015-06-29 08:42
Java7 and above does not work with runescape due to Oracle breaking libawt/libjawt /dylibjawt
And refusing to fix it. This issue could be worked around in Windows and Linux but not on Mac sadly.

Mod Philip have confirmed an official fix is in the workings on twitter for when the new Mac osx gets released

**Comment by HikariKnight** [comment] 2015-09-25 14:49
Implemented as of v4.3.4

**Closed** 2015-09-25 14:50 UTC
Labels: implemented, issue
